import os
import json
from mcp.server.fastmcp import FastMCP
from dotenv import load_dotenv

from src.session import VBulletinSession
from src.persona.scraper import PostScraper
from src.event.poller import fetch_new_posts
from src.event.thread_scraper import fetch_thread_context
from src.event.poster import post_reply as _post_reply
from src.scraper.memberlist import parse_memberlist
from src.scraper.profile import parse_last_active
from src.persona.analyzer import _format_posts, _SCHEMA_DESCRIPTION, _apply_analysis, _select_examples
from src.persona.models import PersonaProfile

load_dotenv()

mcp = FastMCP("Forum Simulator MCP")

_session = None


def get_session() -> VBulletinSession:
    """Singleton session bound to the scanner account."""
    global _session
    if _session is None:
        _session = VBulletinSession()
        username = os.getenv("FORUM_USERNAME")
        password = os.getenv("FORUM_PASSWORD")
        if not username or not password:
            raise RuntimeError("FORUM_USERNAME and FORUM_PASSWORD missing from .env")
        if not _session.login(username, password):
            raise RuntimeError("Failed to login to forum with scanner account")
    return _session


@mcp.tool()
def get_user_posts(username: str, limit: int = 100, before_ts: int | None = None) -> str:
    """Fetch recent forum posts by a specific user.
    
    Args:
        username: The forum username to search for.
        limit: Number of posts to return (default 100). Max 200 per VBulletin limits.
        before_ts: Optional Unix timestamp upper bound (only fetch posts older than this).
    """
    session = get_session()
    scraper = PostScraper(session, delay=6)
    
    posts, oldest_ts = scraper.fetch_window(username, before_ts=before_ts)
    return json.dumps({
        "posts": posts[:limit],
        "oldest_post_ts": oldest_ts
    })


@mcp.tool()
def get_thread_context(post_id: int, n: int = 5) -> str:
    """Fetch the most recent posts inside a thread, leading up to a specific post.
    
    Args:
        post_id: The ID of the post to get context for.
        n: Number of preceding posts to include (default 5).
    """
    session = get_session()
    posts = fetch_thread_context(session, post_id, n=n)
    return json.dumps(posts)


@mcp.tool()
def format_persona_prompt(username: str, filepath: str) -> str:
    """Reads a scratch JSON file of posts and builds the exact prompt string for Persona analysis.
    
    Args:
        username: The forum username being analyzed.
        filepath: Absolute path to the scratch JSON file containing the raw posts.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    # Handle both wrapped {"posts": [...]} and raw array [...]
    posts = data.get("posts", []) if isinstance(data, dict) else data
        
    posts_text = _format_posts(posts)
    
    prompt = (
        f"Analyseer de volgende {len(posts)} forumberichten van gebruiker "
        f'"{username}".\n\n'
        f"Berichten:\n{posts_text}\n\n"
        f"Geef een JSON object terug met dit schema:\n{_SCHEMA_DESCRIPTION}\n\n"
        f"Beperk opinion_fingerprint tot maximaal 25 items — maak ze concreet en bruikbaar als debatpunten. "
        f"Geef enkel het JSON object terug, geen uitleg."
    )
    return prompt


@mcp.tool()
def save_approved_persona(username: str, llm_file: str, raw_posts_file: str, user_id: int | None = None, reversed_username: str | None = None, post_count: int | None = None, last_active: str | None = None) -> str:
    """Hydrates an LLM persona profile with identity fields and saves it to the agent_personas/ folder.
    
    Args:
        username: The forum username being analyzed.
        llm_file: Absolute path to the JSON file generated by the PersonaAnalyzer subagent.
        raw_posts_file: Absolute path to the raw posts JSON file from DataCollector.
        user_id: Optional. The user's numeric forum ID.
        reversed_username: Optional. The reversed version of the username.
        post_count: Optional. The user's total post count.
        last_active: Optional. The user's last active date as an ISO string.
    """
    import re
    from pathlib import Path
    
    alter = None
    approved_accounts_path = Path("config/approved_accounts.json")
    if approved_accounts_path.exists():
        try:
            with open(approved_accounts_path, 'r', encoding='utf-8') as f:
                accounts = json.load(f)
                for a in accounts:
                    if a.get("original_username", "").lower() == username.lower():
                        alter = a
                        break
        except Exception:
            pass
            
    if not alter:
        if user_id is None or reversed_username is None or post_count is None or last_active is None:
            return (f"Error: User '{username}' not found in config/approved_accounts.json. "
                    f"Please ask the user to provide user_id, reversed_username, post_count, and last_active, "
                    f"and call this tool again with those arguments.")
        alter = {
            "user_id": user_id,
            "original_username": username,
            "reversed_username": reversed_username,
            "post_count": post_count,
            "last_active": last_active
        }
        
    profile = PersonaProfile.from_alter_ego(alter)
    
    with open(llm_file, 'r', encoding='utf-8') as f:
        llm_data = json.load(f)
        
    _apply_analysis(profile, llm_data)
    
    with open(raw_posts_file, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)
        
    posts = raw_data.get("posts", []) if isinstance(raw_data, dict) else raw_data
    oldest_ts = raw_data.get("oldest_post_ts", 0) if isinstance(raw_data, dict) else 0
    
    profile.posts_analyzed = len(posts)
    profile.pages_loaded = 1
    profile.oldest_post_ts = oldest_ts
    profile.example_posts = _select_examples(posts)
    profile.is_approved = True
    
    save_dir = Path("agent_personas")
    save_dir.mkdir(exist_ok=True)
    
    safe_name = re.sub(r'[^\w\-]', '_', username)
    save_path = save_dir / f"{safe_name}.json"
    
    with open(save_path, 'w', encoding='utf-8') as f:
        json.dump(profile.to_dict(), f, ensure_ascii=False, indent=2)
        
    return f"Success: Fully hydrated persona saved to {save_path}"


@mcp.tool()
def get_daily_activity() -> str:
    """Fetch the latest posts and active threads across the entire forum from the last 24h."""
    session = get_session()
    posts = fetch_new_posts(session)
    return json.dumps(posts)


@mcp.tool()
def post_reply(username: str, password: str, thread_id: int, message: str) -> bool:
    """Post a reply to a thread acting as a specific forum member.
    
    Args:
        username: The username of the alter-ego to post as.
        password: The password for the alter-ego account.
        thread_id: The ID of the thread to reply to.
        message: The message body to post.
    """
    return _post_reply(username, password, thread_id, message)


@mcp.resource("forum://memberlist/top100")
def get_top_members() -> str:
    """Returns the top 100 members from the forum by post count."""
    session = get_session()
    html = session.get("memberlist.php?order=DESC&sort=posts&pp=100")
    members = parse_memberlist(html)
    return json.dumps([{"user_id": m.user_id, "username": m.username, "post_count": m.post_count, "last_active": m.last_active} for m in members])


@mcp.resource("forum://user/{user_id}/last_active")
def get_user_last_active(user_id: int) -> str:
    """Returns the last active date of a user."""
    session = get_session()
    html = session.get(f"search.php?do=finduser&u={user_id}")
    date = parse_last_active(html)
    date_str = date.isoformat() if hasattr(date, 'isoformat') else str(date)
    return json.dumps({"user_id": user_id, "last_active": date_str})


if __name__ == "__main__":
    mcp.run()
